#!/usr/bin/env bash

export CONTECO_LABEL="Conteco controlplane conteco"
export CONTECO_DESCRIPTION="The Conteco controlplane conteco image."

export CONTECO_TYPE="controlplane"
export CONTECO_NAME="conteco"
export CONTECO_TAG="v1.0.4"

export CONTECO_BASE="controlplane.base"
export CONTECO_BUILD="image"
