#!/usr/bin/env bash

export CONTECO_LABEL="ContEco ${MODECO_TYPE} base module"
export CONTECO_DESCRIPTION="The ContEco ${MODECO_TYPE} base module."

export CONTECO_TYPE="${MODECO_TYPE}"
export CONTECO_NAME="base"
export CONTECO_TAG="v1.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco.base"
